server:
  port: 8081
#  ssl:
#    key-store: /www/wwwroot/位置/keystore.jks
#    key-store-password: 123456
#    key-store-type: jks
#    key-password: 123456
spring:
  data:
    #Redis配置
    redis:
      host: 8.134.***.204
      port: 6379
      # 数据库索引
      database: 0
      # 密码
      password: *****
      # 连接超时时间
      timeout: 10s
      lettuce:
        pool:
          # 连接池中的最小空闲连接
          min-idle: 3
          # 连接池中的最大空闲连接
          max-idle: 8
          # 连接池的最大数据库连接数
          max-active: 10
          # #连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.71.32.189:3306/mangguo?useSSL=true
    username: ****
    password: ****
    initial-size: 10
    max-active: 100
    min-idle: 10
    max-wait: 60000
    pool-prepared-statements: true
    max-pool-prepared-statement-per-connection-size: 20
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    #Oracle需要打开注释
    #validation-query: SELECT 1 FROM DUAL
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    stat-view-servlet:
      enabled: true
      url-pattern: /druid/*
      #login-username: admin
      #login-password: admin
    filter:
      stat:
        log-slow-sql: true
        slow-sql-millis: 1000
        merge-sql: false
      wall:
        config:
          multi-statement-allow: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  mvc:
    throw-exception-if-no-handler-found: true

#mybatis
mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: work.hou6663.mango.model
  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      logic-delete-value: -1
      logic-not-delete-value: 0
    banner: false
  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'

# 日志,生产环境注释即可
logging:
  level:
    work.liy.mango.mapper: debug

spring.jackson.date-format: yyyy-MM-dd HH:mm

#这个是时区，一定要加，否则会默认为格林尼治时间，即少8小时
spring.jackson.time-zone: GMT+8
#
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

oa:
  wx:
    app-id: *****
    app-secret: ******
    msgDataFormat: JSON

# 重复项，后删
wx:
  #微信id和密钥,修改这里
  wxId: *****
  wxSecret: ******


sms:
  appid: 
  appkey: 
  endpoint: 上海
  templateId: 
  sign: 
  sdkId: 
  bucketName: liy1900-1258789570

img:
#  通用
  common: /www/wwwroot/liy/common/
#  头像
  avatar: /www/wwwroot/liy/avaimg/
#  头像访问路径
  avatarHttpImg: https://liy/avaimg/
#  主页轮播图存储地址
  headImg: /www/wwwroot/liy/mangoImg/shop_img/
  headHttpImg: https://liy/mangoImg/shop_img/
#  聊天图片存储地址
  chatImg: /www/wwwroot/liy/mangoImg/user_chat_img/
  chatHttp: https://liy/mangoImg/user_chat_img/
#  商店图片存储地址
  shopImg: /www/wwwroot/liy/mangoImg/shopMessage_img/
  shopHttpImg: https://liy/mangoImg/shopMessage_img/


#腾讯云COS配置
tencent:
  cos:
    #访问域名
    rootSrc: https://liy1900-*********.cos.ap-guangzhou.myqcloud.com
    #所属地域
    bucketAddr: ap-guangzhou
    SecretId: AKIDOj****************GmFd0N
    SecretKey: jdWL5v**************ZSKAuW2UqAS
    #存储桶名称
    bucketName: liy1900-1258789570

# excel 文件配置
excel:
  file:
    cityPath: classpath:static/AMap_adcode_citycode.xlsx

